image: node:14.16.0-buster

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - deploy

cache: &global_cache
  paths:
    - node_modules/ 

deploy-stage:
  stage: deploy
  only:
    - main
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

